version: 2.1
orbs: 
  heroku: circleci/heroku@0.0.10
jobs: 
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: install npm dependencies
          command: |
            npm install --save
      - run:
          name: run unit tests
          command: |
            ./node_modules/mocha/bin/mocha test/ --reporter mochawesome --reporter-options reportDir=test-results,reportFilename=test-results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results 
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            -build
          filters:
            branches:
              only: main